import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Headline from 'components/Headline/Headline'
import JapanMap from 'components/JapanMap/JapanMap'
import Textarea from 'components/Textarea/Textarea'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Headline subject='マスク予報とは' />
        <Textarea text={`あなたの　撮影した写真から　AIがマスク着用率(ちゃくようりつ)を　判定します。\n下の日本地図から　各都道府県（かくとどうふけん）の　マスク着用の状況を　確認することができます！`}/>
        <Headline subject='都道府県を選択' />
        <JapanMap />
        <Headline subject='このサイトで出来ること' />
        <Textarea text={`aaa`}/>
      </main>
    </>
  )
}
