import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Headline from 'components/Headline/Headline'
import JapanMap from 'components/JapanMap/JapanMap'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Headline subject='マスク予報とは' />
        <p>マスク予報とは</p>
        <p>ーーーーーーーー</p>
        <Headline subject='都道府県を選択' />
        <JapanMap />
        <p>ーーーーーーーーー</p>
        <Headline subject='このサイトで出来ること' />
        <p>このサイトで出来ること</p>
        <p>ーーーーーーーーーーーー</p>
      </main>
    </>
  )
}
